Repository rster2002/cs-NoSQL-Project, pull requests merged in 2020-10, with the labels that each got.

#12 Ticket components
  Model/ComboBoxOption.cs
  Model/Model.csproj
  Service/TicketService.cs
  TestConsole/Program.cs
  TestConsole/TestConsole.csproj
  View/MainWindow.Designer.cs
  View/MainWindow.cs
  View/View.csproj
  View/components/CreateTicketComponent.Designer.cs
  View/components/CreateTicketComponent.cs
  View/components/CreateTicketComponent.resx
  View/components/SelectUserComponent.Designer.cs
  View/components/SelectUserComponent.cs
  View/components/SelectUserComponent.resx
  View/views/CreateTicketView.Designer.cs
  View/views/CreateTicketView.cs
  View/views/CreateTicketView.resx
Labels: Feature, Major

#16 TicketDetailComponent
  Model/Ticket.cs
  Model/User.cs
  TestConsole/Program.cs
  View/View.csproj
  View/components/TicketDetailsComponent.Designer.cs
  View/components/TicketDetailsComponent.cs
  View/components/TicketDetailsComponent.resx
Labels: Critical, Feature, WIP

#20 Finished most of the Component and functionality
  DAL/BaseRepo.cs
  DAL/TicketRepo.cs
  Model/Model.csproj
  Model/OpenState.cs
  Model/TicketSelectedEventArgs.cs
  Service/TicketService.cs
  Service/UserSession.cs
  TestConsole/Program.cs
  View/MainWindow.Designer.cs
  View/MainWindow.cs
  View/View.csproj
  View/components/BaseTicketEditorComponent.Designer.cs
  View/components/BaseTicketEditorComponent.cs
  View/components/ChangeTicketComponent.cs
  View/components/CreateTicketComponent.cs
  View/components/Popup.cs
  View/components/SelectUserComponent.Designer.cs
  View/components/SelectUserComponent.cs
  View/components/TicketDetailsComponent.Designer.cs
  View/components/TicketDetailsComponent.cs
  View/components/TicketListView.Designer.cs
  View/components/TicketListView.cs
  View/components/TicketListView.resx
  View/views/CreateTicketView.Designer.cs
  View/views/CreateTicketView.cs
  View/views/TicketManager.Designer.cs
  View/views/TicketManager.cs
  View/views/TicketManager.resx
Labels: Improvement, WIP

#25 User management
  Service/UserService.cs
  Service/packages.config
  View/View.csproj
  View/views/AddUserForm.Designer.cs
  View/views/AddUserForm.cs
  View/views/AddUserForm.resx
  View/views/UserManagement.Designer.cs
  View/views/UserManagement.cs
  View/views/UserManagement.resx
Labels: WIP

#42 Edit and unify the design
  View/MainWindow.Designer.cs
  View/MainWindow.cs
  View/View.csproj
  View/components/ArchiveComponent.Designer.cs
  View/components/ArchiveComponent.cs
  View/components/ArchiveComponent.resx
  View/components/BaseTicketEditorComponent.Designer.cs
  View/components/LoginComponent.Designer.cs
  View/components/LoginComponent.cs
  View/components/SelectUserComponent.Designer.cs
  View/views/AddUserForm.Designer.cs
  View/views/ArchiveView.Designer.cs
  View/views/ArchiveView.cs
  View/views/ArchiveView.resx
  View/views/DashboardView.Designer.cs
  View/views/DashboardView.cs
  View/views/DashboardView.resx
  View/views/EditUserForm.Designer.cs
  View/views/LoginView.cs
  View/views/TicketManager.Designer.cs
  View/views/UserManagement.Designer.cs
Labels: Improvement, WIP
